<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Fpp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Prelude.fs" />
    <EmbeddedResource Include="../../stdlib/prelude.fpp" LogicalName="prelude.fpp" />
    <Compile Include="Syntax/Tokens.fs" />
    <Compile Include="Syntax/Lexer.fs" />
    <Compile Include="Syntax/Tree.fs" />
    <Compile Include="Syntax/Parser.fs" />
    <Compile Include="Syntax/Desugar.fs" />
    <Compile Include="Analysis/Resolve.fs" />
    <Compile Include="Analysis/Types.fs" />
    <Compile Include="Analysis/Format.fs" />
    <Compile Include="Analysis/Classes.fs" />
    <Compile Include="Analysis/Infer.fs" />
    <Compile Include="Core/Core.fs" />
    <Compile Include="Core/Lower.fs" />
    <Compile Include="Core/Lint.fs" />
    <Compile Include="Core/Serialize.fs" />
    <Compile Include="Core/Link.fs" />
    <Compile Include="Core/Optimize.fs" />
    <Compile Include="Core/Plugins.fs" />
    <Compile Include="Backend/WasmBinary.fs" />
    <Compile Include="Backend/EmitBin.fs" />
    <Compile Include="Backend/BinDriver.fs" />
    <Compile Include="Backend/CEmit.fs" />
    <Compile Include="Backend/SourceMap.fs" />
    <Compile Include="Query.fs" />
    <Compile Include="Project.fs" />
    <Compile Include="Workspace.fs" />
  </ItemGroup>

</Project>
