(module
  ;; v0 — generic, values boxed through externref (4 crossings per iteration)
  (import "js" "get"   (func $get   (param externref externref) (result externref)))
  (import "js" "set"   (func $set   (param externref externref externref)))
  (import "js" "num"   (func $num   (param f64) (result externref)))
  (import "js" "toNum" (func $toNum (param externref) (result f64)))
  (import "js" "str"   (func $str   (param i32) (result externref)))
  ;; v1 — generic, but TYPED: the glue converts, so no boxing crossings (2)
  (import "js" "getNum" (func $getNum (param externref externref) (result f64)))
  (import "js" "setNum" (func $setNum (param externref externref f64)))
  ;; v2 — typed AND named by index, so the JS side is a monomorphic accessor (2)
  (import "js" "getNumAt" (func $getNumAt (param externref i32) (result f64)))
  (import "js" "setNumAt" (func $setNumAt (param externref i32 f64)))
  ;; v3 — one import per property: the floor for "a crossing per operation" (2)
  (import "js" "getCounter" (func $getCounter (param externref) (result f64)))
  (import "js" "setCounter" (func $setCounter (param externref f64)))

  (global $nCount (mut externref) (ref.null extern))
  (func (export "initNames") (global.set $nCount (call $str (i32.const 7))))

  (func (export "v0") (param $o externref) (param $n i32)
    (local $i i32)
    (block $d (loop $g (br_if $d (i32.ge_s (local.get $i) (local.get $n)))
      (call $set (local.get $o) (global.get $nCount)
        (call $num (f64.add (call $toNum (call $get (local.get $o) (global.get $nCount))) (f64.const 1))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $g))))

  (func (export "v1") (param $o externref) (param $n i32)
    (local $i i32)
    (block $d (loop $g (br_if $d (i32.ge_s (local.get $i) (local.get $n)))
      (call $setNum (local.get $o) (global.get $nCount)
        (f64.add (call $getNum (local.get $o) (global.get $nCount)) (f64.const 1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $g))))

  (func (export "v2") (param $o externref) (param $n i32)
    (local $i i32)
    (block $d (loop $g (br_if $d (i32.ge_s (local.get $i) (local.get $n)))
      (call $setNumAt (local.get $o) (i32.const 0)
        (f64.add (call $getNumAt (local.get $o) (i32.const 0)) (f64.const 1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $g))))

  (func (export "v3") (param $o externref) (param $n i32)
    (local $i i32)
    (block $d (loop $g (br_if $d (i32.ge_s (local.get $i) (local.get $n)))
      (call $setCounter (local.get $o)
        (f64.add (call $getCounter (local.get $o)) (f64.const 1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $g))))
)
