// GENERATED by tools/webgpu-gen.py — do not edit. The JS half of the
// WebGPU binary protocol: decoders for every descriptor record and
// the command-stream interpreter. Slots are f64: numbers as
// themselves, bools/enums/handles as ints, strings and raw objects
// as indices into the side array, optionals tag-first, sequences
// count-first, records inline.
export const gpuVm = ({ mem, h: H, reg: REG }) => {
  const E_GPUPowerPreference = ["low-power", "high-performance"];
  const E_GPUFeatureName = ["core-features-and-limits", "depth-clip-control", "depth32float-stencil8", "texture-compression-bc", "texture-compression-bc-sliced-3d", "texture-compression-etc2", "texture-compression-astc", "texture-compression-astc-sliced-3d", "timestamp-query", "indirect-first-instance", "shader-f16", "rg11b10ufloat-renderable", "bgra8unorm-storage", "float32-filterable", "float32-blendable", "clip-distances", "dual-source-blending", "subgroups", "texture-formats-tier1", "texture-formats-tier2", "primitive-index", "texture-component-swizzle", "subgroup-size-control"];
  const E_GPUBufferMapState = ["unmapped", "pending", "mapped"];
  const E_GPUTextureDimension = ["1d", "2d", "3d"];
  const E_GPUTextureViewDimension = ["1d", "2d", "2d-array", "cube", "cube-array", "3d"];
  const E_GPUTextureAspect = ["all", "stencil-only", "depth-only"];
  const E_GPUTextureFormat = ["r8unorm", "r8snorm", "r8uint", "r8sint", "r16unorm", "r16snorm", "r16uint", "r16sint", "r16float", "rg8unorm", "rg8snorm", "rg8uint", "rg8sint", "r32uint", "r32sint", "r32float", "rg16unorm", "rg16snorm", "rg16uint", "rg16sint", "rg16float", "rgba8unorm", "rgba8unorm-srgb", "rgba8snorm", "rgba8uint", "rgba8sint", "bgra8unorm", "bgra8unorm-srgb", "rgb9e5ufloat", "rgb10a2uint", "rgb10a2unorm", "rg11b10ufloat", "rg32uint", "rg32sint", "rg32float", "rgba16unorm", "rgba16snorm", "rgba16uint", "rgba16sint", "rgba16float", "rgba32uint", "rgba32sint", "rgba32float", "stencil8", "depth16unorm", "depth24plus", "depth24plus-stencil8", "depth32float", "depth32float-stencil8", "bc1-rgba-unorm", "bc1-rgba-unorm-srgb", "bc2-rgba-unorm", "bc2-rgba-unorm-srgb", "bc3-rgba-unorm", "bc3-rgba-unorm-srgb", "bc4-r-unorm", "bc4-r-snorm", "bc5-rg-unorm", "bc5-rg-snorm", "bc6h-rgb-ufloat", "bc6h-rgb-float", "bc7-rgba-unorm", "bc7-rgba-unorm-srgb", "etc2-rgb8unorm", "etc2-rgb8unorm-srgb", "etc2-rgb8a1unorm", "etc2-rgb8a1unorm-srgb", "etc2-rgba8unorm", "etc2-rgba8unorm-srgb", "eac-r11unorm", "eac-r11snorm", "eac-rg11unorm", "eac-rg11snorm", "astc-4x4-unorm", "astc-4x4-unorm-srgb", "astc-5x4-unorm", "astc-5x4-unorm-srgb", "astc-5x5-unorm", "astc-5x5-unorm-srgb", "astc-6x5-unorm", "astc-6x5-unorm-srgb", "astc-6x6-unorm", "astc-6x6-unorm-srgb", "astc-8x5-unorm", "astc-8x5-unorm-srgb", "astc-8x6-unorm", "astc-8x6-unorm-srgb", "astc-8x8-unorm", "astc-8x8-unorm-srgb", "astc-10x5-unorm", "astc-10x5-unorm-srgb", "astc-10x6-unorm", "astc-10x6-unorm-srgb", "astc-10x8-unorm", "astc-10x8-unorm-srgb", "astc-10x10-unorm", "astc-10x10-unorm-srgb", "astc-12x10-unorm", "astc-12x10-unorm-srgb", "astc-12x12-unorm", "astc-12x12-unorm-srgb"];
  const E_GPUAddressMode = ["clamp-to-edge", "repeat", "mirror-repeat"];
  const E_GPUFilterMode = ["nearest", "linear"];
  const E_GPUMipmapFilterMode = ["nearest", "linear"];
  const E_GPUCompareFunction = ["never", "less", "equal", "less-equal", "greater", "not-equal", "greater-equal", "always"];
  const E_GPUBufferBindingType = ["uniform", "storage", "read-only-storage"];
  const E_GPUSamplerBindingType = ["filtering", "non-filtering", "comparison"];
  const E_GPUTextureSampleType = ["float", "unfilterable-float", "depth", "sint", "uint"];
  const E_GPUStorageTextureAccess = ["write-only", "read-only", "read-write"];
  const E_GPUCompilationMessageType = ["error", "warning", "info"];
  const E_GPUPipelineErrorReason = ["validation", "internal"];
  const E_GPUAutoLayoutMode = ["auto"];
  const E_GPUPrimitiveTopology = ["point-list", "line-list", "line-strip", "triangle-list", "triangle-strip"];
  const E_GPUFrontFace = ["ccw", "cw"];
  const E_GPUCullMode = ["none", "front", "back"];
  const E_GPUBlendFactor = ["zero", "one", "src", "one-minus-src", "src-alpha", "one-minus-src-alpha", "dst", "one-minus-dst", "dst-alpha", "one-minus-dst-alpha", "src-alpha-saturated", "constant", "one-minus-constant", "src1", "one-minus-src1", "src1-alpha", "one-minus-src1-alpha"];
  const E_GPUBlendOperation = ["add", "subtract", "reverse-subtract", "min", "max"];
  const E_GPUStencilOperation = ["keep", "zero", "replace", "invert", "increment-clamp", "decrement-clamp", "increment-wrap", "decrement-wrap"];
  const E_GPUIndexFormat = ["uint16", "uint32"];
  const E_GPUVertexFormat = ["uint8", "uint8x2", "uint8x4", "sint8", "sint8x2", "sint8x4", "unorm8", "unorm8x2", "unorm8x4", "snorm8", "snorm8x2", "snorm8x4", "uint16", "uint16x2", "uint16x4", "sint16", "sint16x2", "sint16x4", "unorm16", "unorm16x2", "unorm16x4", "snorm16", "snorm16x2", "snorm16x4", "float16", "float16x2", "float16x4", "float32", "float32x2", "float32x3", "float32x4", "uint32", "uint32x2", "uint32x3", "uint32x4", "sint32", "sint32x2", "sint32x3", "sint32x4", "unorm10-10-10-2", "unorm8x4-bgra"];
  const E_GPUVertexStepMode = ["vertex", "instance"];
  const E_GPULoadOp = ["load", "clear"];
  const E_GPUStoreOp = ["store", "discard"];
  const E_GPUQueryType = ["occlusion", "timestamp"];
  const E_GPUCanvasAlphaMode = ["opaque", "premultiplied"];
  const E_GPUCanvasToneMappingMode = ["standard", "extended"];
  const E_GPUDeviceLostReason = ["unknown", "destroyed"];
  const E_GPUErrorFilter = ["validation", "out-of-memory", "internal"];
  const D_GPUObjectDescriptorBase = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    return o;
  };
  const D_GPURequestAdapterOptions = (c) => {
    const o = {};
    if (c.a[c.i++]) o.featureLevel = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.powerPreference = E_GPUPowerPreference[c.a[c.i++]];
    if (c.a[c.i++]) o.forceFallbackAdapter = !!c.a[c.i++];
    if (c.a[c.i++]) o.xrCompatible = !!c.a[c.i++];
    return o;
  };
  const D_GPUDeviceDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.requiredFeatures = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = E_GPUFeatureName[c.a[c.i++]]; return r; })();
    if (c.a[c.i++]) o.requiredLimits = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.defaultQueue = D_GPUQueueDescriptor(c);
    return o;
  };
  const D_GPUBufferDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.size = c.a[c.i++];
    o.usage = c.a[c.i++];
    if (c.a[c.i++]) o.mappedAtCreation = !!c.a[c.i++];
    return o;
  };
  const D_GPUTextureDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.size = D_GPUExtent3DDict(c);
    if (c.a[c.i++]) o.mipLevelCount = c.a[c.i++];
    if (c.a[c.i++]) o.sampleCount = c.a[c.i++];
    if (c.a[c.i++]) o.dimension = E_GPUTextureDimension[c.a[c.i++]];
    o.format = E_GPUTextureFormat[c.a[c.i++]];
    o.usage = c.a[c.i++];
    if (c.a[c.i++]) o.viewFormats = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = E_GPUTextureFormat[c.a[c.i++]]; return r; })();
    if (c.a[c.i++]) o.textureBindingViewDimension = E_GPUTextureViewDimension[c.a[c.i++]];
    return o;
  };
  const D_GPUTextureViewDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.format = E_GPUTextureFormat[c.a[c.i++]];
    if (c.a[c.i++]) o.dimension = E_GPUTextureViewDimension[c.a[c.i++]];
    if (c.a[c.i++]) o.usage = c.a[c.i++];
    if (c.a[c.i++]) o.aspect = E_GPUTextureAspect[c.a[c.i++]];
    if (c.a[c.i++]) o.baseMipLevel = c.a[c.i++];
    if (c.a[c.i++]) o.mipLevelCount = c.a[c.i++];
    if (c.a[c.i++]) o.baseArrayLayer = c.a[c.i++];
    if (c.a[c.i++]) o.arrayLayerCount = c.a[c.i++];
    if (c.a[c.i++]) o.swizzle = c.s[c.a[c.i++]];
    return o;
  };
  const D_GPUExternalTextureDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.source = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.colorSpace = c.s[c.a[c.i++]];
    return o;
  };
  const D_GPUSamplerDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.addressModeU = E_GPUAddressMode[c.a[c.i++]];
    if (c.a[c.i++]) o.addressModeV = E_GPUAddressMode[c.a[c.i++]];
    if (c.a[c.i++]) o.addressModeW = E_GPUAddressMode[c.a[c.i++]];
    if (c.a[c.i++]) o.magFilter = E_GPUFilterMode[c.a[c.i++]];
    if (c.a[c.i++]) o.minFilter = E_GPUFilterMode[c.a[c.i++]];
    if (c.a[c.i++]) o.mipmapFilter = E_GPUMipmapFilterMode[c.a[c.i++]];
    if (c.a[c.i++]) o.lodMinClamp = c.a[c.i++];
    if (c.a[c.i++]) o.lodMaxClamp = c.a[c.i++];
    if (c.a[c.i++]) o.compare = E_GPUCompareFunction[c.a[c.i++]];
    if (c.a[c.i++]) o.maxAnisotropy = c.a[c.i++];
    return o;
  };
  const D_GPUBindGroupLayoutDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.entries = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPUBindGroupLayoutEntry(c); return r; })();
    return o;
  };
  const D_GPUBindGroupLayoutEntry = (c) => {
    const o = {};
    o.binding = c.a[c.i++];
    o.visibility = c.a[c.i++];
    if (c.a[c.i++]) o.buffer = D_GPUBufferBindingLayout(c);
    if (c.a[c.i++]) o.sampler = D_GPUSamplerBindingLayout(c);
    if (c.a[c.i++]) o.texture = D_GPUTextureBindingLayout(c);
    if (c.a[c.i++]) o.storageTexture = D_GPUStorageTextureBindingLayout(c);
    if (c.a[c.i++]) o.externalTexture = D_GPUExternalTextureBindingLayout(c);
    return o;
  };
  const D_GPUBufferBindingLayout = (c) => {
    const o = {};
    if (c.a[c.i++]) o.type = E_GPUBufferBindingType[c.a[c.i++]];
    if (c.a[c.i++]) o.hasDynamicOffset = !!c.a[c.i++];
    if (c.a[c.i++]) o.minBindingSize = c.a[c.i++];
    return o;
  };
  const D_GPUSamplerBindingLayout = (c) => {
    const o = {};
    if (c.a[c.i++]) o.type = E_GPUSamplerBindingType[c.a[c.i++]];
    return o;
  };
  const D_GPUTextureBindingLayout = (c) => {
    const o = {};
    if (c.a[c.i++]) o.sampleType = E_GPUTextureSampleType[c.a[c.i++]];
    if (c.a[c.i++]) o.viewDimension = E_GPUTextureViewDimension[c.a[c.i++]];
    if (c.a[c.i++]) o.multisampled = !!c.a[c.i++];
    return o;
  };
  const D_GPUStorageTextureBindingLayout = (c) => {
    const o = {};
    if (c.a[c.i++]) o.access = E_GPUStorageTextureAccess[c.a[c.i++]];
    o.format = E_GPUTextureFormat[c.a[c.i++]];
    if (c.a[c.i++]) o.viewDimension = E_GPUTextureViewDimension[c.a[c.i++]];
    return o;
  };
  const D_GPUExternalTextureBindingLayout = (c) => {
    const o = {};
    return o;
  };
  const D_GPUBindGroupDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.layout = H(c.a[c.i++]);
    o.entries = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPUBindGroupEntry(c); return r; })();
    return o;
  };
  const D_GPUBindGroupEntry = (c) => {
    const o = {};
    o.binding = c.a[c.i++];
    o.resource = c.s[c.a[c.i++]];
    return o;
  };
  const D_GPUBufferBinding = (c) => {
    const o = {};
    o.buffer = H(c.a[c.i++]);
    if (c.a[c.i++]) o.offset = c.a[c.i++];
    if (c.a[c.i++]) o.size = c.a[c.i++];
    return o;
  };
  const D_GPUPipelineLayoutDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.bindGroupLayouts = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = H(c.a[c.i++]); return r; })();
    if (c.a[c.i++]) o.immediateSize = c.a[c.i++];
    return o;
  };
  const D_GPUShaderModuleDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.code = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.compilationHints = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPUShaderModuleCompilationHint(c); return r; })();
    return o;
  };
  const D_GPUShaderModuleCompilationHint = (c) => {
    const o = {};
    o.entryPoint = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.layout = E_GPUAutoLayoutMode[c.a[c.i++]];
    return o;
  };
  const D_GPUPipelineErrorInit = (c) => {
    const o = {};
    o.reason = E_GPUPipelineErrorReason[c.a[c.i++]];
    return o;
  };
  const D_GPUPipelineDescriptorBase = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.layout = E_GPUAutoLayoutMode[c.a[c.i++]];
    return o;
  };
  const D_GPUProgrammableStage = (c) => {
    const o = {};
    o.module = H(c.a[c.i++]);
    if (c.a[c.i++]) o.entryPoint = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.constants = c.s[c.a[c.i++]];
    return o;
  };
  const D_GPUComputePipelineDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.layout = E_GPUAutoLayoutMode[c.a[c.i++]];
    o.compute = D_GPUProgrammableStage(c);
    return o;
  };
  const D_GPURenderPipelineDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.layout = E_GPUAutoLayoutMode[c.a[c.i++]];
    o.vertex = D_GPUVertexState(c);
    if (c.a[c.i++]) o.primitive = D_GPUPrimitiveState(c);
    if (c.a[c.i++]) o.depthStencil = D_GPUDepthStencilState(c);
    if (c.a[c.i++]) o.multisample = D_GPUMultisampleState(c);
    if (c.a[c.i++]) o.fragment = D_GPUFragmentState(c);
    return o;
  };
  const D_GPUPrimitiveState = (c) => {
    const o = {};
    if (c.a[c.i++]) o.topology = E_GPUPrimitiveTopology[c.a[c.i++]];
    if (c.a[c.i++]) o.stripIndexFormat = E_GPUIndexFormat[c.a[c.i++]];
    if (c.a[c.i++]) o.frontFace = E_GPUFrontFace[c.a[c.i++]];
    if (c.a[c.i++]) o.cullMode = E_GPUCullMode[c.a[c.i++]];
    if (c.a[c.i++]) o.unclippedDepth = !!c.a[c.i++];
    return o;
  };
  const D_GPUMultisampleState = (c) => {
    const o = {};
    if (c.a[c.i++]) o.count = c.a[c.i++];
    if (c.a[c.i++]) o.mask = c.a[c.i++];
    if (c.a[c.i++]) o.alphaToCoverageEnabled = !!c.a[c.i++];
    return o;
  };
  const D_GPUFragmentState = (c) => {
    const o = {};
    o.module = H(c.a[c.i++]);
    if (c.a[c.i++]) o.entryPoint = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.constants = c.s[c.a[c.i++]];
    o.targets = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPUColorTargetState(c); return r; })();
    return o;
  };
  const D_GPUColorTargetState = (c) => {
    const o = {};
    o.format = E_GPUTextureFormat[c.a[c.i++]];
    if (c.a[c.i++]) o.blend = D_GPUBlendState(c);
    if (c.a[c.i++]) o.writeMask = c.a[c.i++];
    return o;
  };
  const D_GPUBlendState = (c) => {
    const o = {};
    o.color = D_GPUBlendComponent(c);
    o.alpha = D_GPUBlendComponent(c);
    return o;
  };
  const D_GPUBlendComponent = (c) => {
    const o = {};
    if (c.a[c.i++]) o.operation = E_GPUBlendOperation[c.a[c.i++]];
    if (c.a[c.i++]) o.srcFactor = E_GPUBlendFactor[c.a[c.i++]];
    if (c.a[c.i++]) o.dstFactor = E_GPUBlendFactor[c.a[c.i++]];
    return o;
  };
  const D_GPUDepthStencilState = (c) => {
    const o = {};
    o.format = E_GPUTextureFormat[c.a[c.i++]];
    if (c.a[c.i++]) o.depthWriteEnabled = !!c.a[c.i++];
    if (c.a[c.i++]) o.depthCompare = E_GPUCompareFunction[c.a[c.i++]];
    if (c.a[c.i++]) o.stencilFront = D_GPUStencilFaceState(c);
    if (c.a[c.i++]) o.stencilBack = D_GPUStencilFaceState(c);
    if (c.a[c.i++]) o.stencilReadMask = c.a[c.i++];
    if (c.a[c.i++]) o.stencilWriteMask = c.a[c.i++];
    if (c.a[c.i++]) o.depthBias = c.a[c.i++];
    if (c.a[c.i++]) o.depthBiasSlopeScale = c.a[c.i++];
    if (c.a[c.i++]) o.depthBiasClamp = c.a[c.i++];
    return o;
  };
  const D_GPUStencilFaceState = (c) => {
    const o = {};
    if (c.a[c.i++]) o.compare = E_GPUCompareFunction[c.a[c.i++]];
    if (c.a[c.i++]) o.failOp = E_GPUStencilOperation[c.a[c.i++]];
    if (c.a[c.i++]) o.depthFailOp = E_GPUStencilOperation[c.a[c.i++]];
    if (c.a[c.i++]) o.passOp = E_GPUStencilOperation[c.a[c.i++]];
    return o;
  };
  const D_GPUVertexState = (c) => {
    const o = {};
    o.module = H(c.a[c.i++]);
    if (c.a[c.i++]) o.entryPoint = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.constants = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.buffers = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPUVertexBufferLayout(c); return r; })();
    return o;
  };
  const D_GPUVertexBufferLayout = (c) => {
    const o = {};
    o.arrayStride = c.a[c.i++];
    if (c.a[c.i++]) o.stepMode = E_GPUVertexStepMode[c.a[c.i++]];
    o.attributes = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPUVertexAttribute(c); return r; })();
    return o;
  };
  const D_GPUVertexAttribute = (c) => {
    const o = {};
    o.format = E_GPUVertexFormat[c.a[c.i++]];
    o.offset = c.a[c.i++];
    o.shaderLocation = c.a[c.i++];
    return o;
  };
  const D_GPUTexelCopyBufferLayout = (c) => {
    const o = {};
    if (c.a[c.i++]) o.offset = c.a[c.i++];
    if (c.a[c.i++]) o.bytesPerRow = c.a[c.i++];
    if (c.a[c.i++]) o.rowsPerImage = c.a[c.i++];
    return o;
  };
  const D_GPUTexelCopyBufferInfo = (c) => {
    const o = {};
    if (c.a[c.i++]) o.offset = c.a[c.i++];
    if (c.a[c.i++]) o.bytesPerRow = c.a[c.i++];
    if (c.a[c.i++]) o.rowsPerImage = c.a[c.i++];
    o.buffer = H(c.a[c.i++]);
    return o;
  };
  const D_GPUTexelCopyTextureInfo = (c) => {
    const o = {};
    o.texture = H(c.a[c.i++]);
    if (c.a[c.i++]) o.mipLevel = c.a[c.i++];
    if (c.a[c.i++]) o.origin = D_GPUOrigin3DDict(c);
    if (c.a[c.i++]) o.aspect = E_GPUTextureAspect[c.a[c.i++]];
    return o;
  };
  const D_GPUCopyExternalImageDestInfo = (c) => {
    const o = {};
    o.texture = H(c.a[c.i++]);
    if (c.a[c.i++]) o.mipLevel = c.a[c.i++];
    if (c.a[c.i++]) o.origin = D_GPUOrigin3DDict(c);
    if (c.a[c.i++]) o.aspect = E_GPUTextureAspect[c.a[c.i++]];
    if (c.a[c.i++]) o.colorSpace = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.premultipliedAlpha = !!c.a[c.i++];
    return o;
  };
  const D_GPUCopyExternalImageSourceInfo = (c) => {
    const o = {};
    o.source = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.origin = D_GPUOrigin2DDict(c);
    if (c.a[c.i++]) o.flipY = !!c.a[c.i++];
    return o;
  };
  const D_GPUCommandBufferDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    return o;
  };
  const D_GPUCommandEncoderDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    return o;
  };
  const D_GPUComputePassTimestampWrites = (c) => {
    const o = {};
    o.querySet = H(c.a[c.i++]);
    if (c.a[c.i++]) o.beginningOfPassWriteIndex = c.a[c.i++];
    if (c.a[c.i++]) o.endOfPassWriteIndex = c.a[c.i++];
    return o;
  };
  const D_GPUComputePassDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.timestampWrites = D_GPUComputePassTimestampWrites(c);
    return o;
  };
  const D_GPURenderPassTimestampWrites = (c) => {
    const o = {};
    o.querySet = H(c.a[c.i++]);
    if (c.a[c.i++]) o.beginningOfPassWriteIndex = c.a[c.i++];
    if (c.a[c.i++]) o.endOfPassWriteIndex = c.a[c.i++];
    return o;
  };
  const D_GPURenderPassDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.colorAttachments = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPURenderPassColorAttachment(c); return r; })();
    if (c.a[c.i++]) o.depthStencilAttachment = D_GPURenderPassDepthStencilAttachment(c);
    if (c.a[c.i++]) o.occlusionQuerySet = H(c.a[c.i++]);
    if (c.a[c.i++]) o.timestampWrites = D_GPURenderPassTimestampWrites(c);
    if (c.a[c.i++]) o.maxDrawCount = c.a[c.i++];
    return o;
  };
  const D_GPURenderPassColorAttachment = (c) => {
    const o = {};
    o.view = H(c.a[c.i++]);
    if (c.a[c.i++]) o.depthSlice = c.a[c.i++];
    if (c.a[c.i++]) o.resolveTarget = H(c.a[c.i++]);
    if (c.a[c.i++]) o.clearValue = D_GPUColorDict(c);
    o.loadOp = E_GPULoadOp[c.a[c.i++]];
    o.storeOp = E_GPUStoreOp[c.a[c.i++]];
    return o;
  };
  const D_GPURenderPassDepthStencilAttachment = (c) => {
    const o = {};
    o.view = H(c.a[c.i++]);
    if (c.a[c.i++]) o.depthClearValue = c.a[c.i++];
    if (c.a[c.i++]) o.depthLoadOp = E_GPULoadOp[c.a[c.i++]];
    if (c.a[c.i++]) o.depthStoreOp = E_GPUStoreOp[c.a[c.i++]];
    if (c.a[c.i++]) o.depthReadOnly = !!c.a[c.i++];
    if (c.a[c.i++]) o.stencilClearValue = c.a[c.i++];
    if (c.a[c.i++]) o.stencilLoadOp = E_GPULoadOp[c.a[c.i++]];
    if (c.a[c.i++]) o.stencilStoreOp = E_GPUStoreOp[c.a[c.i++]];
    if (c.a[c.i++]) o.stencilReadOnly = !!c.a[c.i++];
    return o;
  };
  const D_GPURenderPassLayout = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.colorFormats = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = E_GPUTextureFormat[c.a[c.i++]]; return r; })();
    if (c.a[c.i++]) o.depthStencilFormat = E_GPUTextureFormat[c.a[c.i++]];
    if (c.a[c.i++]) o.sampleCount = c.a[c.i++];
    return o;
  };
  const D_GPURenderBundleDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    return o;
  };
  const D_GPURenderBundleEncoderDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.colorFormats = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = E_GPUTextureFormat[c.a[c.i++]]; return r; })();
    if (c.a[c.i++]) o.depthStencilFormat = E_GPUTextureFormat[c.a[c.i++]];
    if (c.a[c.i++]) o.sampleCount = c.a[c.i++];
    if (c.a[c.i++]) o.depthReadOnly = !!c.a[c.i++];
    if (c.a[c.i++]) o.stencilReadOnly = !!c.a[c.i++];
    return o;
  };
  const D_GPUQueueDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    return o;
  };
  const D_GPUQuerySetDescriptor = (c) => {
    const o = {};
    if (c.a[c.i++]) o.label = c.s[c.a[c.i++]];
    o.type = E_GPUQueryType[c.a[c.i++]];
    o.count = c.a[c.i++];
    return o;
  };
  const D_GPUCanvasToneMapping = (c) => {
    const o = {};
    if (c.a[c.i++]) o.mode = E_GPUCanvasToneMappingMode[c.a[c.i++]];
    return o;
  };
  const D_GPUCanvasConfiguration = (c) => {
    const o = {};
    o.device = H(c.a[c.i++]);
    o.format = E_GPUTextureFormat[c.a[c.i++]];
    if (c.a[c.i++]) o.usage = c.a[c.i++];
    if (c.a[c.i++]) o.viewFormats = (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = E_GPUTextureFormat[c.a[c.i++]]; return r; })();
    if (c.a[c.i++]) o.colorSpace = c.s[c.a[c.i++]];
    if (c.a[c.i++]) o.toneMapping = D_GPUCanvasToneMapping(c);
    if (c.a[c.i++]) o.alphaMode = E_GPUCanvasAlphaMode[c.a[c.i++]];
    return o;
  };
  const D_GPUUncapturedErrorEventInit = (c) => {
    const o = {};
    o.error = H(c.a[c.i++]);
    return o;
  };
  const D_GPUColorDict = (c) => {
    const o = {};
    o.r = c.a[c.i++];
    o.g = c.a[c.i++];
    o.b = c.a[c.i++];
    o.a = c.a[c.i++];
    return o;
  };
  const D_GPUOrigin2DDict = (c) => {
    const o = {};
    if (c.a[c.i++]) o.x = c.a[c.i++];
    if (c.a[c.i++]) o.y = c.a[c.i++];
    return o;
  };
  const D_GPUOrigin3DDict = (c) => {
    const o = {};
    if (c.a[c.i++]) o.x = c.a[c.i++];
    if (c.a[c.i++]) o.y = c.a[c.i++];
    if (c.a[c.i++]) o.z = c.a[c.i++];
    return o;
  };
  const D_GPUExtent3DDict = (c) => {
    const o = {};
    o.width = c.a[c.i++];
    if (c.a[c.i++]) o.height = c.a[c.i++];
    if (c.a[c.i++]) o.depthOrArrayLayers = c.a[c.i++];
    return o;
  };
  const M = [
    /* 0 GPUDevice.destroy */ (c) => H(c.a[c.i++]).destroy(),
    /* 1 GPUDevice.createBuffer */ (c) => REG(H(c.a[c.i++]).createBuffer(D_GPUBufferDescriptor(c))),
    /* 2 GPUDevice.createTexture */ (c) => REG(H(c.a[c.i++]).createTexture(D_GPUTextureDescriptor(c))),
    /* 3 GPUDevice.createSampler */ (c) => REG(H(c.a[c.i++]).createSampler((c.a[c.i++] ? D_GPUSamplerDescriptor(c) : undefined))),
    /* 4 GPUDevice.importExternalTexture */ (c) => REG(H(c.a[c.i++]).importExternalTexture(D_GPUExternalTextureDescriptor(c))),
    /* 5 GPUDevice.createBindGroupLayout */ (c) => REG(H(c.a[c.i++]).createBindGroupLayout(D_GPUBindGroupLayoutDescriptor(c))),
    /* 6 GPUDevice.createPipelineLayout */ (c) => REG(H(c.a[c.i++]).createPipelineLayout(D_GPUPipelineLayoutDescriptor(c))),
    /* 7 GPUDevice.createBindGroup */ (c) => REG(H(c.a[c.i++]).createBindGroup(D_GPUBindGroupDescriptor(c))),
    /* 8 GPUDevice.createShaderModule */ (c) => REG(H(c.a[c.i++]).createShaderModule(D_GPUShaderModuleDescriptor(c))),
    /* 9 GPUDevice.createComputePipeline */ (c) => REG(H(c.a[c.i++]).createComputePipeline(D_GPUComputePipelineDescriptor(c))),
    /* 10 GPUDevice.createRenderPipeline */ (c) => REG(H(c.a[c.i++]).createRenderPipeline(D_GPURenderPipelineDescriptor(c))),
    /* 11 GPUDevice.createCommandEncoder */ (c) => REG(H(c.a[c.i++]).createCommandEncoder((c.a[c.i++] ? D_GPUCommandEncoderDescriptor(c) : undefined))),
    /* 12 GPUDevice.createRenderBundleEncoder */ (c) => REG(H(c.a[c.i++]).createRenderBundleEncoder(D_GPURenderBundleEncoderDescriptor(c))),
    /* 13 GPUDevice.createQuerySet */ (c) => REG(H(c.a[c.i++]).createQuerySet(D_GPUQuerySetDescriptor(c))),
    /* 14 GPUDevice.pushErrorScope */ (c) => H(c.a[c.i++]).pushErrorScope(E_GPUErrorFilter[c.a[c.i++]]),
    /* 15 GPUBuffer.unmap */ (c) => H(c.a[c.i++]).unmap(),
    /* 16 GPUBuffer.destroy */ (c) => H(c.a[c.i++]).destroy(),
    /* 17 GPUTexture.createView */ (c) => REG(H(c.a[c.i++]).createView((c.a[c.i++] ? D_GPUTextureViewDescriptor(c) : undefined))),
    /* 18 GPUTexture.destroy */ (c) => H(c.a[c.i++]).destroy(),
    /* 19 GPUComputePipeline.getBindGroupLayout */ (c) => REG(H(c.a[c.i++]).getBindGroupLayout(c.a[c.i++])),
    /* 20 GPURenderPipeline.getBindGroupLayout */ (c) => REG(H(c.a[c.i++]).getBindGroupLayout(c.a[c.i++])),
    /* 21 GPUCommandEncoder.beginRenderPass */ (c) => REG(H(c.a[c.i++]).beginRenderPass(D_GPURenderPassDescriptor(c))),
    /* 22 GPUCommandEncoder.beginComputePass */ (c) => REG(H(c.a[c.i++]).beginComputePass((c.a[c.i++] ? D_GPUComputePassDescriptor(c) : undefined))),
    /* 23 GPUCommandEncoder.copyBufferToBuffer */ (c) => H(c.a[c.i++]).copyBufferToBuffer(H(c.a[c.i++]), H(c.a[c.i++]), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 24 GPUCommandEncoder.copyBufferToTexture */ (c) => H(c.a[c.i++]).copyBufferToTexture(D_GPUTexelCopyBufferInfo(c), D_GPUTexelCopyTextureInfo(c), D_GPUExtent3DDict(c)),
    /* 25 GPUCommandEncoder.copyTextureToBuffer */ (c) => H(c.a[c.i++]).copyTextureToBuffer(D_GPUTexelCopyTextureInfo(c), D_GPUTexelCopyBufferInfo(c), D_GPUExtent3DDict(c)),
    /* 26 GPUCommandEncoder.copyTextureToTexture */ (c) => H(c.a[c.i++]).copyTextureToTexture(D_GPUTexelCopyTextureInfo(c), D_GPUTexelCopyTextureInfo(c), D_GPUExtent3DDict(c)),
    /* 27 GPUCommandEncoder.clearBuffer */ (c) => H(c.a[c.i++]).clearBuffer(H(c.a[c.i++]), (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 28 GPUCommandEncoder.resolveQuerySet */ (c) => H(c.a[c.i++]).resolveQuerySet(H(c.a[c.i++]), c.a[c.i++], c.a[c.i++], H(c.a[c.i++]), c.a[c.i++]),
    /* 29 GPUCommandEncoder.finish */ (c) => REG(H(c.a[c.i++]).finish((c.a[c.i++] ? D_GPUCommandBufferDescriptor(c) : undefined))),
    /* 30 GPUCommandEncoder.pushDebugGroup */ (c) => H(c.a[c.i++]).pushDebugGroup(c.s[c.a[c.i++]]),
    /* 31 GPUCommandEncoder.popDebugGroup */ (c) => H(c.a[c.i++]).popDebugGroup(),
    /* 32 GPUCommandEncoder.insertDebugMarker */ (c) => H(c.a[c.i++]).insertDebugMarker(c.s[c.a[c.i++]]),
    /* 33 GPUComputePassEncoder.setPipeline */ (c) => H(c.a[c.i++]).setPipeline(H(c.a[c.i++])),
    /* 34 GPUComputePassEncoder.dispatchWorkgroups */ (c) => H(c.a[c.i++]).dispatchWorkgroups(c.a[c.i++], (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 35 GPUComputePassEncoder.dispatchWorkgroupsIndirect */ (c) => H(c.a[c.i++]).dispatchWorkgroupsIndirect(H(c.a[c.i++]), c.a[c.i++]),
    /* 36 GPUComputePassEncoder.end */ (c) => H(c.a[c.i++]).end(),
    /* 37 GPUComputePassEncoder.pushDebugGroup */ (c) => H(c.a[c.i++]).pushDebugGroup(c.s[c.a[c.i++]]),
    /* 38 GPUComputePassEncoder.popDebugGroup */ (c) => H(c.a[c.i++]).popDebugGroup(),
    /* 39 GPUComputePassEncoder.insertDebugMarker */ (c) => H(c.a[c.i++]).insertDebugMarker(c.s[c.a[c.i++]]),
    /* 40 GPUComputePassEncoder.setBindGroup */ (c) => H(c.a[c.i++]).setBindGroup(c.a[c.i++], H(c.a[c.i++]), (c.a[c.i++] ? (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = c.a[c.i++]; return r; })() : undefined)),
    /* 41 GPUComputePassEncoder.setImmediates */ (c) => H(c.a[c.i++]).setImmediates(c.a[c.i++], c.s[c.a[c.i++]], (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 42 GPURenderPassEncoder.setViewport */ (c) => H(c.a[c.i++]).setViewport(c.a[c.i++], c.a[c.i++], c.a[c.i++], c.a[c.i++], c.a[c.i++], c.a[c.i++]),
    /* 43 GPURenderPassEncoder.setScissorRect */ (c) => H(c.a[c.i++]).setScissorRect(c.a[c.i++], c.a[c.i++], c.a[c.i++], c.a[c.i++]),
    /* 44 GPURenderPassEncoder.setBlendConstant */ (c) => H(c.a[c.i++]).setBlendConstant(D_GPUColorDict(c)),
    /* 45 GPURenderPassEncoder.setStencilReference */ (c) => H(c.a[c.i++]).setStencilReference(c.a[c.i++]),
    /* 46 GPURenderPassEncoder.beginOcclusionQuery */ (c) => H(c.a[c.i++]).beginOcclusionQuery(c.a[c.i++]),
    /* 47 GPURenderPassEncoder.endOcclusionQuery */ (c) => H(c.a[c.i++]).endOcclusionQuery(),
    /* 48 GPURenderPassEncoder.executeBundles */ (c) => H(c.a[c.i++]).executeBundles((() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = H(c.a[c.i++]); return r; })()),
    /* 49 GPURenderPassEncoder.end */ (c) => H(c.a[c.i++]).end(),
    /* 50 GPURenderPassEncoder.pushDebugGroup */ (c) => H(c.a[c.i++]).pushDebugGroup(c.s[c.a[c.i++]]),
    /* 51 GPURenderPassEncoder.popDebugGroup */ (c) => H(c.a[c.i++]).popDebugGroup(),
    /* 52 GPURenderPassEncoder.insertDebugMarker */ (c) => H(c.a[c.i++]).insertDebugMarker(c.s[c.a[c.i++]]),
    /* 53 GPURenderPassEncoder.setBindGroup */ (c) => H(c.a[c.i++]).setBindGroup(c.a[c.i++], H(c.a[c.i++]), (c.a[c.i++] ? (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = c.a[c.i++]; return r; })() : undefined)),
    /* 54 GPURenderPassEncoder.setImmediates */ (c) => H(c.a[c.i++]).setImmediates(c.a[c.i++], c.s[c.a[c.i++]], (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 55 GPURenderPassEncoder.setPipeline */ (c) => H(c.a[c.i++]).setPipeline(H(c.a[c.i++])),
    /* 56 GPURenderPassEncoder.setIndexBuffer */ (c) => H(c.a[c.i++]).setIndexBuffer(H(c.a[c.i++]), E_GPUIndexFormat[c.a[c.i++]], (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 57 GPURenderPassEncoder.setVertexBuffer */ (c) => H(c.a[c.i++]).setVertexBuffer(c.a[c.i++], H(c.a[c.i++]), (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 58 GPURenderPassEncoder.draw */ (c) => H(c.a[c.i++]).draw(c.a[c.i++], (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 59 GPURenderPassEncoder.drawIndexed */ (c) => H(c.a[c.i++]).drawIndexed(c.a[c.i++], (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 60 GPURenderPassEncoder.drawIndirect */ (c) => H(c.a[c.i++]).drawIndirect(H(c.a[c.i++]), c.a[c.i++]),
    /* 61 GPURenderPassEncoder.drawIndexedIndirect */ (c) => H(c.a[c.i++]).drawIndexedIndirect(H(c.a[c.i++]), c.a[c.i++]),
    /* 62 GPURenderBundleEncoder.finish */ (c) => REG(H(c.a[c.i++]).finish((c.a[c.i++] ? D_GPURenderBundleDescriptor(c) : undefined))),
    /* 63 GPURenderBundleEncoder.pushDebugGroup */ (c) => H(c.a[c.i++]).pushDebugGroup(c.s[c.a[c.i++]]),
    /* 64 GPURenderBundleEncoder.popDebugGroup */ (c) => H(c.a[c.i++]).popDebugGroup(),
    /* 65 GPURenderBundleEncoder.insertDebugMarker */ (c) => H(c.a[c.i++]).insertDebugMarker(c.s[c.a[c.i++]]),
    /* 66 GPURenderBundleEncoder.setBindGroup */ (c) => H(c.a[c.i++]).setBindGroup(c.a[c.i++], H(c.a[c.i++]), (c.a[c.i++] ? (() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = c.a[c.i++]; return r; })() : undefined)),
    /* 67 GPURenderBundleEncoder.setImmediates */ (c) => H(c.a[c.i++]).setImmediates(c.a[c.i++], c.s[c.a[c.i++]], (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 68 GPURenderBundleEncoder.setPipeline */ (c) => H(c.a[c.i++]).setPipeline(H(c.a[c.i++])),
    /* 69 GPURenderBundleEncoder.setIndexBuffer */ (c) => H(c.a[c.i++]).setIndexBuffer(H(c.a[c.i++]), E_GPUIndexFormat[c.a[c.i++]], (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 70 GPURenderBundleEncoder.setVertexBuffer */ (c) => H(c.a[c.i++]).setVertexBuffer(c.a[c.i++], H(c.a[c.i++]), (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 71 GPURenderBundleEncoder.draw */ (c) => H(c.a[c.i++]).draw(c.a[c.i++], (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 72 GPURenderBundleEncoder.drawIndexed */ (c) => H(c.a[c.i++]).drawIndexed(c.a[c.i++], (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 73 GPURenderBundleEncoder.drawIndirect */ (c) => H(c.a[c.i++]).drawIndirect(H(c.a[c.i++]), c.a[c.i++]),
    /* 74 GPURenderBundleEncoder.drawIndexedIndirect */ (c) => H(c.a[c.i++]).drawIndexedIndirect(H(c.a[c.i++]), c.a[c.i++]),
    /* 75 GPUQueue.submit */ (c) => H(c.a[c.i++]).submit((() => { const m = c.a[c.i++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = H(c.a[c.i++]); return r; })()),
    /* 76 GPUQueue.writeBuffer */ (c) => H(c.a[c.i++]).writeBuffer(H(c.a[c.i++]), c.a[c.i++], c.s[c.a[c.i++]], (c.a[c.i++] ? c.a[c.i++] : undefined), (c.a[c.i++] ? c.a[c.i++] : undefined)),
    /* 77 GPUQueue.writeTexture */ (c) => H(c.a[c.i++]).writeTexture(D_GPUTexelCopyTextureInfo(c), c.s[c.a[c.i++]], D_GPUTexelCopyBufferLayout(c), D_GPUExtent3DDict(c)),
    /* 78 GPUQueue.copyExternalImageToTexture */ (c) => H(c.a[c.i++]).copyExternalImageToTexture(D_GPUCopyExternalImageSourceInfo(c), D_GPUCopyExternalImageDestInfo(c), D_GPUExtent3DDict(c)),
    /* 79 GPUQuerySet.destroy */ (c) => H(c.a[c.i++]).destroy(),
    /* 80 GPUCanvasContext.configure */ (c) => H(c.a[c.i++]).configure(D_GPUCanvasConfiguration(c)),
    /* 81 GPUCanvasContext.unconfigure */ (c) => H(c.a[c.i++]).unconfigure(),
    /* 82 GPUCanvasContext.getCurrentTexture */ (c) => REG(H(c.a[c.i++]).getCurrentTexture()),
  ];
  return { gpuRun: (p, n, s) => {
    const c = { a: new Float64Array(mem(), p >>> 0, n), i: 0, s };
    let r = 0;
    while (c.i < n) r = M[c.a[c.i++]](c);
    return typeof r === 'number' ? r : (r ? 1 : 0);
  } };
};
