// GENERATED by tools/webgpu-gen.py — do not edit. The JS half of the
// WebGPU binary protocol: decoders for every descriptor record and
// the command-stream interpreter. Slots are f64: numbers as
// themselves, bools/enums/handles as ints, strings and raw objects
// as indices into the side array, optionals tag-first, sequences
// count-first, records inline.
export const gpuVm = ({ mem, h: H, reg: REG }) => {
  // the cursor: module-scope lets, set per gpuRun, register-friendly
  let A = null, I = 0, S = null;
  const E_GPUPowerPreference = ["low-power", "high-performance"];
  const E_GPUFeatureName = ["core-features-and-limits", "depth-clip-control", "depth32float-stencil8", "texture-compression-bc", "texture-compression-bc-sliced-3d", "texture-compression-etc2", "texture-compression-astc", "texture-compression-astc-sliced-3d", "timestamp-query", "indirect-first-instance", "shader-f16", "rg11b10ufloat-renderable", "bgra8unorm-storage", "float32-filterable", "float32-blendable", "clip-distances", "dual-source-blending", "subgroups", "texture-formats-tier1", "texture-formats-tier2", "primitive-index", "texture-component-swizzle", "subgroup-size-control"];
  const E_GPUBufferMapState = ["unmapped", "pending", "mapped"];
  const E_GPUTextureDimension = ["1d", "2d", "3d"];
  const E_GPUTextureViewDimension = ["1d", "2d", "2d-array", "cube", "cube-array", "3d"];
  const E_GPUTextureAspect = ["all", "stencil-only", "depth-only"];
  const E_GPUTextureFormat = ["r8unorm", "r8snorm", "r8uint", "r8sint", "r16unorm", "r16snorm", "r16uint", "r16sint", "r16float", "rg8unorm", "rg8snorm", "rg8uint", "rg8sint", "r32uint", "r32sint", "r32float", "rg16unorm", "rg16snorm", "rg16uint", "rg16sint", "rg16float", "rgba8unorm", "rgba8unorm-srgb", "rgba8snorm", "rgba8uint", "rgba8sint", "bgra8unorm", "bgra8unorm-srgb", "rgb9e5ufloat", "rgb10a2uint", "rgb10a2unorm", "rg11b10ufloat", "rg32uint", "rg32sint", "rg32float", "rgba16unorm", "rgba16snorm", "rgba16uint", "rgba16sint", "rgba16float", "rgba32uint", "rgba32sint", "rgba32float", "stencil8", "depth16unorm", "depth24plus", "depth24plus-stencil8", "depth32float", "depth32float-stencil8", "bc1-rgba-unorm", "bc1-rgba-unorm-srgb", "bc2-rgba-unorm", "bc2-rgba-unorm-srgb", "bc3-rgba-unorm", "bc3-rgba-unorm-srgb", "bc4-r-unorm", "bc4-r-snorm", "bc5-rg-unorm", "bc5-rg-snorm", "bc6h-rgb-ufloat", "bc6h-rgb-float", "bc7-rgba-unorm", "bc7-rgba-unorm-srgb", "etc2-rgb8unorm", "etc2-rgb8unorm-srgb", "etc2-rgb8a1unorm", "etc2-rgb8a1unorm-srgb", "etc2-rgba8unorm", "etc2-rgba8unorm-srgb", "eac-r11unorm", "eac-r11snorm", "eac-rg11unorm", "eac-rg11snorm", "astc-4x4-unorm", "astc-4x4-unorm-srgb", "astc-5x4-unorm", "astc-5x4-unorm-srgb", "astc-5x5-unorm", "astc-5x5-unorm-srgb", "astc-6x5-unorm", "astc-6x5-unorm-srgb", "astc-6x6-unorm", "astc-6x6-unorm-srgb", "astc-8x5-unorm", "astc-8x5-unorm-srgb", "astc-8x6-unorm", "astc-8x6-unorm-srgb", "astc-8x8-unorm", "astc-8x8-unorm-srgb", "astc-10x5-unorm", "astc-10x5-unorm-srgb", "astc-10x6-unorm", "astc-10x6-unorm-srgb", "astc-10x8-unorm", "astc-10x8-unorm-srgb", "astc-10x10-unorm", "astc-10x10-unorm-srgb", "astc-12x10-unorm", "astc-12x10-unorm-srgb", "astc-12x12-unorm", "astc-12x12-unorm-srgb"];
  const E_GPUAddressMode = ["clamp-to-edge", "repeat", "mirror-repeat"];
  const E_GPUFilterMode = ["nearest", "linear"];
  const E_GPUMipmapFilterMode = ["nearest", "linear"];
  const E_GPUCompareFunction = ["never", "less", "equal", "less-equal", "greater", "not-equal", "greater-equal", "always"];
  const E_GPUBufferBindingType = ["uniform", "storage", "read-only-storage"];
  const E_GPUSamplerBindingType = ["filtering", "non-filtering", "comparison"];
  const E_GPUTextureSampleType = ["float", "unfilterable-float", "depth", "sint", "uint"];
  const E_GPUStorageTextureAccess = ["write-only", "read-only", "read-write"];
  const E_GPUCompilationMessageType = ["error", "warning", "info"];
  const E_GPUPipelineErrorReason = ["validation", "internal"];
  const E_GPUAutoLayoutMode = ["auto"];
  const E_GPUPrimitiveTopology = ["point-list", "line-list", "line-strip", "triangle-list", "triangle-strip"];
  const E_GPUFrontFace = ["ccw", "cw"];
  const E_GPUCullMode = ["none", "front", "back"];
  const E_GPUBlendFactor = ["zero", "one", "src", "one-minus-src", "src-alpha", "one-minus-src-alpha", "dst", "one-minus-dst", "dst-alpha", "one-minus-dst-alpha", "src-alpha-saturated", "constant", "one-minus-constant", "src1", "one-minus-src1", "src1-alpha", "one-minus-src1-alpha"];
  const E_GPUBlendOperation = ["add", "subtract", "reverse-subtract", "min", "max"];
  const E_GPUStencilOperation = ["keep", "zero", "replace", "invert", "increment-clamp", "decrement-clamp", "increment-wrap", "decrement-wrap"];
  const E_GPUIndexFormat = ["uint16", "uint32"];
  const E_GPUVertexFormat = ["uint8", "uint8x2", "uint8x4", "sint8", "sint8x2", "sint8x4", "unorm8", "unorm8x2", "unorm8x4", "snorm8", "snorm8x2", "snorm8x4", "uint16", "uint16x2", "uint16x4", "sint16", "sint16x2", "sint16x4", "unorm16", "unorm16x2", "unorm16x4", "snorm16", "snorm16x2", "snorm16x4", "float16", "float16x2", "float16x4", "float32", "float32x2", "float32x3", "float32x4", "uint32", "uint32x2", "uint32x3", "uint32x4", "sint32", "sint32x2", "sint32x3", "sint32x4", "unorm10-10-10-2", "unorm8x4-bgra"];
  const E_GPUVertexStepMode = ["vertex", "instance"];
  const E_GPULoadOp = ["load", "clear"];
  const E_GPUStoreOp = ["store", "discard"];
  const E_GPUQueryType = ["occlusion", "timestamp"];
  const E_GPUCanvasAlphaMode = ["opaque", "premultiplied"];
  const E_GPUCanvasToneMappingMode = ["standard", "extended"];
  const E_GPUDeviceLostReason = ["unknown", "destroyed"];
  const E_GPUErrorFilter = ["validation", "out-of-memory", "internal"];
  const D_GPUObjectDescriptorBase = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    return o;
  };
  const D_GPURequestAdapterOptions = () => {
    const o = {};
    if (A[I++]) o.featureLevel = S[A[I++]];
    if (A[I++]) o.powerPreference = E_GPUPowerPreference[A[I++]];
    if (A[I++]) o.forceFallbackAdapter = !!A[I++];
    if (A[I++]) o.xrCompatible = !!A[I++];
    return o;
  };
  const D_GPUDeviceDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    if (A[I++]) o.requiredFeatures = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = E_GPUFeatureName[A[I++]]; return r; })();
    if (A[I++]) o.requiredLimits = S[A[I++]];
    if (A[I++]) o.defaultQueue = D_GPUQueueDescriptor();
    return o;
  };
  const D_GPUBufferDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.size = A[I++];
    o.usage = A[I++];
    if (A[I++]) o.mappedAtCreation = !!A[I++];
    return o;
  };
  const D_GPUTextureDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.size = D_GPUExtent3DDict();
    if (A[I++]) o.mipLevelCount = A[I++];
    if (A[I++]) o.sampleCount = A[I++];
    if (A[I++]) o.dimension = E_GPUTextureDimension[A[I++]];
    o.format = E_GPUTextureFormat[A[I++]];
    o.usage = A[I++];
    if (A[I++]) o.viewFormats = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = E_GPUTextureFormat[A[I++]]; return r; })();
    if (A[I++]) o.textureBindingViewDimension = E_GPUTextureViewDimension[A[I++]];
    return o;
  };
  const D_GPUTextureViewDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    if (A[I++]) o.format = E_GPUTextureFormat[A[I++]];
    if (A[I++]) o.dimension = E_GPUTextureViewDimension[A[I++]];
    if (A[I++]) o.usage = A[I++];
    if (A[I++]) o.aspect = E_GPUTextureAspect[A[I++]];
    if (A[I++]) o.baseMipLevel = A[I++];
    if (A[I++]) o.mipLevelCount = A[I++];
    if (A[I++]) o.baseArrayLayer = A[I++];
    if (A[I++]) o.arrayLayerCount = A[I++];
    if (A[I++]) o.swizzle = S[A[I++]];
    return o;
  };
  const D_GPUExternalTextureDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.source = S[A[I++]];
    if (A[I++]) o.colorSpace = S[A[I++]];
    return o;
  };
  const D_GPUSamplerDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    if (A[I++]) o.addressModeU = E_GPUAddressMode[A[I++]];
    if (A[I++]) o.addressModeV = E_GPUAddressMode[A[I++]];
    if (A[I++]) o.addressModeW = E_GPUAddressMode[A[I++]];
    if (A[I++]) o.magFilter = E_GPUFilterMode[A[I++]];
    if (A[I++]) o.minFilter = E_GPUFilterMode[A[I++]];
    if (A[I++]) o.mipmapFilter = E_GPUMipmapFilterMode[A[I++]];
    if (A[I++]) o.lodMinClamp = A[I++];
    if (A[I++]) o.lodMaxClamp = A[I++];
    if (A[I++]) o.compare = E_GPUCompareFunction[A[I++]];
    if (A[I++]) o.maxAnisotropy = A[I++];
    return o;
  };
  const D_GPUBindGroupLayoutDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.entries = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPUBindGroupLayoutEntry(); return r; })();
    return o;
  };
  const D_GPUBindGroupLayoutEntry = () => {
    const o = {};
    o.binding = A[I++];
    o.visibility = A[I++];
    if (A[I++]) o.buffer = D_GPUBufferBindingLayout();
    if (A[I++]) o.sampler = D_GPUSamplerBindingLayout();
    if (A[I++]) o.texture = D_GPUTextureBindingLayout();
    if (A[I++]) o.storageTexture = D_GPUStorageTextureBindingLayout();
    if (A[I++]) o.externalTexture = D_GPUExternalTextureBindingLayout();
    return o;
  };
  const D_GPUBufferBindingLayout = () => {
    const o = {};
    if (A[I++]) o.type = E_GPUBufferBindingType[A[I++]];
    if (A[I++]) o.hasDynamicOffset = !!A[I++];
    if (A[I++]) o.minBindingSize = A[I++];
    return o;
  };
  const D_GPUSamplerBindingLayout = () => {
    const o = {};
    if (A[I++]) o.type = E_GPUSamplerBindingType[A[I++]];
    return o;
  };
  const D_GPUTextureBindingLayout = () => {
    const o = {};
    if (A[I++]) o.sampleType = E_GPUTextureSampleType[A[I++]];
    if (A[I++]) o.viewDimension = E_GPUTextureViewDimension[A[I++]];
    if (A[I++]) o.multisampled = !!A[I++];
    return o;
  };
  const D_GPUStorageTextureBindingLayout = () => {
    const o = {};
    if (A[I++]) o.access = E_GPUStorageTextureAccess[A[I++]];
    o.format = E_GPUTextureFormat[A[I++]];
    if (A[I++]) o.viewDimension = E_GPUTextureViewDimension[A[I++]];
    return o;
  };
  const D_GPUExternalTextureBindingLayout = () => {
    const o = {};
    return o;
  };
  const D_GPUBindGroupDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.layout = H(A[I++]);
    o.entries = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPUBindGroupEntry(); return r; })();
    return o;
  };
  const D_GPUBindGroupEntry = () => {
    const o = {};
    o.binding = A[I++];
    o.resource = S[A[I++]];
    return o;
  };
  const D_GPUBufferBinding = () => {
    const o = {};
    o.buffer = H(A[I++]);
    if (A[I++]) o.offset = A[I++];
    if (A[I++]) o.size = A[I++];
    return o;
  };
  const D_GPUPipelineLayoutDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.bindGroupLayouts = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = H(A[I++]); return r; })();
    if (A[I++]) o.immediateSize = A[I++];
    return o;
  };
  const D_GPUShaderModuleDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.code = S[A[I++]];
    if (A[I++]) o.compilationHints = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPUShaderModuleCompilationHint(); return r; })();
    return o;
  };
  const D_GPUShaderModuleCompilationHint = () => {
    const o = {};
    o.entryPoint = S[A[I++]];
    if (A[I++]) o.layout = E_GPUAutoLayoutMode[A[I++]];
    return o;
  };
  const D_GPUPipelineErrorInit = () => {
    const o = {};
    o.reason = E_GPUPipelineErrorReason[A[I++]];
    return o;
  };
  const D_GPUPipelineDescriptorBase = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.layout = E_GPUAutoLayoutMode[A[I++]];
    return o;
  };
  const D_GPUProgrammableStage = () => {
    const o = {};
    o.module = H(A[I++]);
    if (A[I++]) o.entryPoint = S[A[I++]];
    if (A[I++]) o.constants = S[A[I++]];
    return o;
  };
  const D_GPUComputePipelineDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.layout = E_GPUAutoLayoutMode[A[I++]];
    o.compute = D_GPUProgrammableStage();
    return o;
  };
  const D_GPURenderPipelineDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.layout = E_GPUAutoLayoutMode[A[I++]];
    o.vertex = D_GPUVertexState();
    if (A[I++]) o.primitive = D_GPUPrimitiveState();
    if (A[I++]) o.depthStencil = D_GPUDepthStencilState();
    if (A[I++]) o.multisample = D_GPUMultisampleState();
    if (A[I++]) o.fragment = D_GPUFragmentState();
    return o;
  };
  const D_GPUPrimitiveState = () => {
    const o = {};
    if (A[I++]) o.topology = E_GPUPrimitiveTopology[A[I++]];
    if (A[I++]) o.stripIndexFormat = E_GPUIndexFormat[A[I++]];
    if (A[I++]) o.frontFace = E_GPUFrontFace[A[I++]];
    if (A[I++]) o.cullMode = E_GPUCullMode[A[I++]];
    if (A[I++]) o.unclippedDepth = !!A[I++];
    return o;
  };
  const D_GPUMultisampleState = () => {
    const o = {};
    if (A[I++]) o.count = A[I++];
    if (A[I++]) o.mask = A[I++];
    if (A[I++]) o.alphaToCoverageEnabled = !!A[I++];
    return o;
  };
  const D_GPUFragmentState = () => {
    const o = {};
    o.module = H(A[I++]);
    if (A[I++]) o.entryPoint = S[A[I++]];
    if (A[I++]) o.constants = S[A[I++]];
    o.targets = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPUColorTargetState(); return r; })();
    return o;
  };
  const D_GPUColorTargetState = () => {
    const o = {};
    o.format = E_GPUTextureFormat[A[I++]];
    if (A[I++]) o.blend = D_GPUBlendState();
    if (A[I++]) o.writeMask = A[I++];
    return o;
  };
  const D_GPUBlendState = () => {
    const o = {};
    o.color = D_GPUBlendComponent();
    o.alpha = D_GPUBlendComponent();
    return o;
  };
  const D_GPUBlendComponent = () => {
    const o = {};
    if (A[I++]) o.operation = E_GPUBlendOperation[A[I++]];
    if (A[I++]) o.srcFactor = E_GPUBlendFactor[A[I++]];
    if (A[I++]) o.dstFactor = E_GPUBlendFactor[A[I++]];
    return o;
  };
  const D_GPUDepthStencilState = () => {
    const o = {};
    o.format = E_GPUTextureFormat[A[I++]];
    if (A[I++]) o.depthWriteEnabled = !!A[I++];
    if (A[I++]) o.depthCompare = E_GPUCompareFunction[A[I++]];
    if (A[I++]) o.stencilFront = D_GPUStencilFaceState();
    if (A[I++]) o.stencilBack = D_GPUStencilFaceState();
    if (A[I++]) o.stencilReadMask = A[I++];
    if (A[I++]) o.stencilWriteMask = A[I++];
    if (A[I++]) o.depthBias = A[I++];
    if (A[I++]) o.depthBiasSlopeScale = A[I++];
    if (A[I++]) o.depthBiasClamp = A[I++];
    return o;
  };
  const D_GPUStencilFaceState = () => {
    const o = {};
    if (A[I++]) o.compare = E_GPUCompareFunction[A[I++]];
    if (A[I++]) o.failOp = E_GPUStencilOperation[A[I++]];
    if (A[I++]) o.depthFailOp = E_GPUStencilOperation[A[I++]];
    if (A[I++]) o.passOp = E_GPUStencilOperation[A[I++]];
    return o;
  };
  const D_GPUVertexState = () => {
    const o = {};
    o.module = H(A[I++]);
    if (A[I++]) o.entryPoint = S[A[I++]];
    if (A[I++]) o.constants = S[A[I++]];
    if (A[I++]) o.buffers = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPUVertexBufferLayout(); return r; })();
    return o;
  };
  const D_GPUVertexBufferLayout = () => {
    const o = {};
    o.arrayStride = A[I++];
    if (A[I++]) o.stepMode = E_GPUVertexStepMode[A[I++]];
    o.attributes = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPUVertexAttribute(); return r; })();
    return o;
  };
  const D_GPUVertexAttribute = () => {
    const o = {};
    o.format = E_GPUVertexFormat[A[I++]];
    o.offset = A[I++];
    o.shaderLocation = A[I++];
    return o;
  };
  const D_GPUTexelCopyBufferLayout = () => {
    const o = {};
    if (A[I++]) o.offset = A[I++];
    if (A[I++]) o.bytesPerRow = A[I++];
    if (A[I++]) o.rowsPerImage = A[I++];
    return o;
  };
  const D_GPUTexelCopyBufferInfo = () => {
    const o = {};
    if (A[I++]) o.offset = A[I++];
    if (A[I++]) o.bytesPerRow = A[I++];
    if (A[I++]) o.rowsPerImage = A[I++];
    o.buffer = H(A[I++]);
    return o;
  };
  const D_GPUTexelCopyTextureInfo = () => {
    const o = {};
    o.texture = H(A[I++]);
    if (A[I++]) o.mipLevel = A[I++];
    if (A[I++]) o.origin = D_GPUOrigin3DDict();
    if (A[I++]) o.aspect = E_GPUTextureAspect[A[I++]];
    return o;
  };
  const D_GPUCopyExternalImageDestInfo = () => {
    const o = {};
    o.texture = H(A[I++]);
    if (A[I++]) o.mipLevel = A[I++];
    if (A[I++]) o.origin = D_GPUOrigin3DDict();
    if (A[I++]) o.aspect = E_GPUTextureAspect[A[I++]];
    if (A[I++]) o.colorSpace = S[A[I++]];
    if (A[I++]) o.premultipliedAlpha = !!A[I++];
    return o;
  };
  const D_GPUCopyExternalImageSourceInfo = () => {
    const o = {};
    o.source = S[A[I++]];
    if (A[I++]) o.origin = D_GPUOrigin2DDict();
    if (A[I++]) o.flipY = !!A[I++];
    return o;
  };
  const D_GPUCommandBufferDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    return o;
  };
  const D_GPUCommandEncoderDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    return o;
  };
  const D_GPUComputePassTimestampWrites = () => {
    const o = {};
    o.querySet = H(A[I++]);
    if (A[I++]) o.beginningOfPassWriteIndex = A[I++];
    if (A[I++]) o.endOfPassWriteIndex = A[I++];
    return o;
  };
  const D_GPUComputePassDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    if (A[I++]) o.timestampWrites = D_GPUComputePassTimestampWrites();
    return o;
  };
  const D_GPURenderPassTimestampWrites = () => {
    const o = {};
    o.querySet = H(A[I++]);
    if (A[I++]) o.beginningOfPassWriteIndex = A[I++];
    if (A[I++]) o.endOfPassWriteIndex = A[I++];
    return o;
  };
  const D_GPURenderPassDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.colorAttachments = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = D_GPURenderPassColorAttachment(); return r; })();
    if (A[I++]) o.depthStencilAttachment = D_GPURenderPassDepthStencilAttachment();
    if (A[I++]) o.occlusionQuerySet = H(A[I++]);
    if (A[I++]) o.timestampWrites = D_GPURenderPassTimestampWrites();
    if (A[I++]) o.maxDrawCount = A[I++];
    return o;
  };
  const D_GPURenderPassColorAttachment = () => {
    const o = {};
    o.view = H(A[I++]);
    if (A[I++]) o.depthSlice = A[I++];
    if (A[I++]) o.resolveTarget = H(A[I++]);
    if (A[I++]) o.clearValue = D_GPUColorDict();
    o.loadOp = E_GPULoadOp[A[I++]];
    o.storeOp = E_GPUStoreOp[A[I++]];
    return o;
  };
  const D_GPURenderPassDepthStencilAttachment = () => {
    const o = {};
    o.view = H(A[I++]);
    if (A[I++]) o.depthClearValue = A[I++];
    if (A[I++]) o.depthLoadOp = E_GPULoadOp[A[I++]];
    if (A[I++]) o.depthStoreOp = E_GPUStoreOp[A[I++]];
    if (A[I++]) o.depthReadOnly = !!A[I++];
    if (A[I++]) o.stencilClearValue = A[I++];
    if (A[I++]) o.stencilLoadOp = E_GPULoadOp[A[I++]];
    if (A[I++]) o.stencilStoreOp = E_GPUStoreOp[A[I++]];
    if (A[I++]) o.stencilReadOnly = !!A[I++];
    return o;
  };
  const D_GPURenderPassLayout = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.colorFormats = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = E_GPUTextureFormat[A[I++]]; return r; })();
    if (A[I++]) o.depthStencilFormat = E_GPUTextureFormat[A[I++]];
    if (A[I++]) o.sampleCount = A[I++];
    return o;
  };
  const D_GPURenderBundleDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    return o;
  };
  const D_GPURenderBundleEncoderDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.colorFormats = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = E_GPUTextureFormat[A[I++]]; return r; })();
    if (A[I++]) o.depthStencilFormat = E_GPUTextureFormat[A[I++]];
    if (A[I++]) o.sampleCount = A[I++];
    if (A[I++]) o.depthReadOnly = !!A[I++];
    if (A[I++]) o.stencilReadOnly = !!A[I++];
    return o;
  };
  const D_GPUQueueDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    return o;
  };
  const D_GPUQuerySetDescriptor = () => {
    const o = {};
    if (A[I++]) o.label = S[A[I++]];
    o.type = E_GPUQueryType[A[I++]];
    o.count = A[I++];
    return o;
  };
  const D_GPUCanvasToneMapping = () => {
    const o = {};
    if (A[I++]) o.mode = E_GPUCanvasToneMappingMode[A[I++]];
    return o;
  };
  const D_GPUCanvasConfiguration = () => {
    const o = {};
    o.device = H(A[I++]);
    o.format = E_GPUTextureFormat[A[I++]];
    if (A[I++]) o.usage = A[I++];
    if (A[I++]) o.viewFormats = (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = E_GPUTextureFormat[A[I++]]; return r; })();
    if (A[I++]) o.colorSpace = S[A[I++]];
    if (A[I++]) o.toneMapping = D_GPUCanvasToneMapping();
    if (A[I++]) o.alphaMode = E_GPUCanvasAlphaMode[A[I++]];
    return o;
  };
  const D_GPUUncapturedErrorEventInit = () => {
    const o = {};
    o.error = H(A[I++]);
    return o;
  };
  const D_GPUColorDict = () => {
    const o = {};
    o.r = A[I++];
    o.g = A[I++];
    o.b = A[I++];
    o.a = A[I++];
    return o;
  };
  const D_GPUOrigin2DDict = () => {
    const o = {};
    if (A[I++]) o.x = A[I++];
    if (A[I++]) o.y = A[I++];
    return o;
  };
  const D_GPUOrigin3DDict = () => {
    const o = {};
    if (A[I++]) o.x = A[I++];
    if (A[I++]) o.y = A[I++];
    if (A[I++]) o.z = A[I++];
    return o;
  };
  const D_GPUExtent3DDict = () => {
    const o = {};
    o.width = A[I++];
    if (A[I++]) o.height = A[I++];
    if (A[I++]) o.depthOrArrayLayers = A[I++];
    return o;
  };
  const M = [
    /* 0 GPUDevice.destroy */ () => H(A[I++]).destroy(),
    /* 1 GPUDevice.createBuffer */ () => REG(H(A[I++]).createBuffer(D_GPUBufferDescriptor())),
    /* 2 GPUDevice.createTexture */ () => REG(H(A[I++]).createTexture(D_GPUTextureDescriptor())),
    /* 3 GPUDevice.createSampler */ () => REG(H(A[I++]).createSampler((A[I++] ? D_GPUSamplerDescriptor() : undefined))),
    /* 4 GPUDevice.importExternalTexture */ () => REG(H(A[I++]).importExternalTexture(D_GPUExternalTextureDescriptor())),
    /* 5 GPUDevice.createBindGroupLayout */ () => REG(H(A[I++]).createBindGroupLayout(D_GPUBindGroupLayoutDescriptor())),
    /* 6 GPUDevice.createPipelineLayout */ () => REG(H(A[I++]).createPipelineLayout(D_GPUPipelineLayoutDescriptor())),
    /* 7 GPUDevice.createBindGroup */ () => REG(H(A[I++]).createBindGroup(D_GPUBindGroupDescriptor())),
    /* 8 GPUDevice.createShaderModule */ () => REG(H(A[I++]).createShaderModule(D_GPUShaderModuleDescriptor())),
    /* 9 GPUDevice.createComputePipeline */ () => REG(H(A[I++]).createComputePipeline(D_GPUComputePipelineDescriptor())),
    /* 10 GPUDevice.createRenderPipeline */ () => REG(H(A[I++]).createRenderPipeline(D_GPURenderPipelineDescriptor())),
    /* 11 GPUDevice.createCommandEncoder */ () => REG(H(A[I++]).createCommandEncoder((A[I++] ? D_GPUCommandEncoderDescriptor() : undefined))),
    /* 12 GPUDevice.createRenderBundleEncoder */ () => REG(H(A[I++]).createRenderBundleEncoder(D_GPURenderBundleEncoderDescriptor())),
    /* 13 GPUDevice.createQuerySet */ () => REG(H(A[I++]).createQuerySet(D_GPUQuerySetDescriptor())),
    /* 14 GPUDevice.pushErrorScope */ () => H(A[I++]).pushErrorScope(E_GPUErrorFilter[A[I++]]),
    /* 15 GPUBuffer.unmap */ () => H(A[I++]).unmap(),
    /* 16 GPUBuffer.destroy */ () => H(A[I++]).destroy(),
    /* 17 GPUTexture.createView */ () => REG(H(A[I++]).createView((A[I++] ? D_GPUTextureViewDescriptor() : undefined))),
    /* 18 GPUTexture.destroy */ () => H(A[I++]).destroy(),
    /* 19 GPUComputePipeline.getBindGroupLayout */ () => REG(H(A[I++]).getBindGroupLayout(A[I++])),
    /* 20 GPURenderPipeline.getBindGroupLayout */ () => REG(H(A[I++]).getBindGroupLayout(A[I++])),
    /* 21 GPUCommandEncoder.beginRenderPass */ () => REG(H(A[I++]).beginRenderPass(D_GPURenderPassDescriptor())),
    /* 22 GPUCommandEncoder.beginComputePass */ () => REG(H(A[I++]).beginComputePass((A[I++] ? D_GPUComputePassDescriptor() : undefined))),
    /* 23 GPUCommandEncoder.copyBufferToBuffer */ () => H(A[I++]).copyBufferToBuffer(H(A[I++]), H(A[I++]), (A[I++] ? A[I++] : undefined)),
    /* 24 GPUCommandEncoder.copyBufferToTexture */ () => H(A[I++]).copyBufferToTexture(D_GPUTexelCopyBufferInfo(), D_GPUTexelCopyTextureInfo(), D_GPUExtent3DDict()),
    /* 25 GPUCommandEncoder.copyTextureToBuffer */ () => H(A[I++]).copyTextureToBuffer(D_GPUTexelCopyTextureInfo(), D_GPUTexelCopyBufferInfo(), D_GPUExtent3DDict()),
    /* 26 GPUCommandEncoder.copyTextureToTexture */ () => H(A[I++]).copyTextureToTexture(D_GPUTexelCopyTextureInfo(), D_GPUTexelCopyTextureInfo(), D_GPUExtent3DDict()),
    /* 27 GPUCommandEncoder.clearBuffer */ () => H(A[I++]).clearBuffer(H(A[I++]), (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 28 GPUCommandEncoder.resolveQuerySet */ () => H(A[I++]).resolveQuerySet(H(A[I++]), A[I++], A[I++], H(A[I++]), A[I++]),
    /* 29 GPUCommandEncoder.finish */ () => REG(H(A[I++]).finish((A[I++] ? D_GPUCommandBufferDescriptor() : undefined))),
    /* 30 GPUCommandEncoder.pushDebugGroup */ () => H(A[I++]).pushDebugGroup(S[A[I++]]),
    /* 31 GPUCommandEncoder.popDebugGroup */ () => H(A[I++]).popDebugGroup(),
    /* 32 GPUCommandEncoder.insertDebugMarker */ () => H(A[I++]).insertDebugMarker(S[A[I++]]),
    /* 33 GPUComputePassEncoder.setPipeline */ () => H(A[I++]).setPipeline(H(A[I++])),
    /* 34 GPUComputePassEncoder.dispatchWorkgroups */ () => H(A[I++]).dispatchWorkgroups(A[I++], (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 35 GPUComputePassEncoder.dispatchWorkgroupsIndirect */ () => H(A[I++]).dispatchWorkgroupsIndirect(H(A[I++]), A[I++]),
    /* 36 GPUComputePassEncoder.end */ () => H(A[I++]).end(),
    /* 37 GPUComputePassEncoder.pushDebugGroup */ () => H(A[I++]).pushDebugGroup(S[A[I++]]),
    /* 38 GPUComputePassEncoder.popDebugGroup */ () => H(A[I++]).popDebugGroup(),
    /* 39 GPUComputePassEncoder.insertDebugMarker */ () => H(A[I++]).insertDebugMarker(S[A[I++]]),
    /* 40 GPUComputePassEncoder.setBindGroup */ () => H(A[I++]).setBindGroup(A[I++], H(A[I++]), (A[I++] ? (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = A[I++]; return r; })() : undefined)),
    /* 41 GPUComputePassEncoder.setImmediates */ () => H(A[I++]).setImmediates(A[I++], S[A[I++]], (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 42 GPURenderPassEncoder.setViewport */ () => H(A[I++]).setViewport(A[I++], A[I++], A[I++], A[I++], A[I++], A[I++]),
    /* 43 GPURenderPassEncoder.setScissorRect */ () => H(A[I++]).setScissorRect(A[I++], A[I++], A[I++], A[I++]),
    /* 44 GPURenderPassEncoder.setBlendConstant */ () => H(A[I++]).setBlendConstant(D_GPUColorDict()),
    /* 45 GPURenderPassEncoder.setStencilReference */ () => H(A[I++]).setStencilReference(A[I++]),
    /* 46 GPURenderPassEncoder.beginOcclusionQuery */ () => H(A[I++]).beginOcclusionQuery(A[I++]),
    /* 47 GPURenderPassEncoder.endOcclusionQuery */ () => H(A[I++]).endOcclusionQuery(),
    /* 48 GPURenderPassEncoder.executeBundles */ () => H(A[I++]).executeBundles((() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = H(A[I++]); return r; })()),
    /* 49 GPURenderPassEncoder.end */ () => H(A[I++]).end(),
    /* 50 GPURenderPassEncoder.pushDebugGroup */ () => H(A[I++]).pushDebugGroup(S[A[I++]]),
    /* 51 GPURenderPassEncoder.popDebugGroup */ () => H(A[I++]).popDebugGroup(),
    /* 52 GPURenderPassEncoder.insertDebugMarker */ () => H(A[I++]).insertDebugMarker(S[A[I++]]),
    /* 53 GPURenderPassEncoder.setBindGroup */ () => H(A[I++]).setBindGroup(A[I++], H(A[I++]), (A[I++] ? (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = A[I++]; return r; })() : undefined)),
    /* 54 GPURenderPassEncoder.setImmediates */ () => H(A[I++]).setImmediates(A[I++], S[A[I++]], (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 55 GPURenderPassEncoder.setPipeline */ () => H(A[I++]).setPipeline(H(A[I++])),
    /* 56 GPURenderPassEncoder.setIndexBuffer */ () => H(A[I++]).setIndexBuffer(H(A[I++]), E_GPUIndexFormat[A[I++]], (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 57 GPURenderPassEncoder.setVertexBuffer */ () => H(A[I++]).setVertexBuffer(A[I++], H(A[I++]), (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 58 GPURenderPassEncoder.draw */ () => H(A[I++]).draw(A[I++], (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 59 GPURenderPassEncoder.drawIndexed */ () => H(A[I++]).drawIndexed(A[I++], (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 60 GPURenderPassEncoder.drawIndirect */ () => H(A[I++]).drawIndirect(H(A[I++]), A[I++]),
    /* 61 GPURenderPassEncoder.drawIndexedIndirect */ () => H(A[I++]).drawIndexedIndirect(H(A[I++]), A[I++]),
    /* 62 GPURenderBundleEncoder.finish */ () => REG(H(A[I++]).finish((A[I++] ? D_GPURenderBundleDescriptor() : undefined))),
    /* 63 GPURenderBundleEncoder.pushDebugGroup */ () => H(A[I++]).pushDebugGroup(S[A[I++]]),
    /* 64 GPURenderBundleEncoder.popDebugGroup */ () => H(A[I++]).popDebugGroup(),
    /* 65 GPURenderBundleEncoder.insertDebugMarker */ () => H(A[I++]).insertDebugMarker(S[A[I++]]),
    /* 66 GPURenderBundleEncoder.setBindGroup */ () => H(A[I++]).setBindGroup(A[I++], H(A[I++]), (A[I++] ? (() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = A[I++]; return r; })() : undefined)),
    /* 67 GPURenderBundleEncoder.setImmediates */ () => H(A[I++]).setImmediates(A[I++], S[A[I++]], (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 68 GPURenderBundleEncoder.setPipeline */ () => H(A[I++]).setPipeline(H(A[I++])),
    /* 69 GPURenderBundleEncoder.setIndexBuffer */ () => H(A[I++]).setIndexBuffer(H(A[I++]), E_GPUIndexFormat[A[I++]], (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 70 GPURenderBundleEncoder.setVertexBuffer */ () => H(A[I++]).setVertexBuffer(A[I++], H(A[I++]), (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 71 GPURenderBundleEncoder.draw */ () => H(A[I++]).draw(A[I++], (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 72 GPURenderBundleEncoder.drawIndexed */ () => H(A[I++]).drawIndexed(A[I++], (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 73 GPURenderBundleEncoder.drawIndirect */ () => H(A[I++]).drawIndirect(H(A[I++]), A[I++]),
    /* 74 GPURenderBundleEncoder.drawIndexedIndirect */ () => H(A[I++]).drawIndexedIndirect(H(A[I++]), A[I++]),
    /* 75 GPUQueue.submit */ () => H(A[I++]).submit((() => { const m = A[I++], r = new Array(m); for (let j = 0; j < m; j++) r[j] = H(A[I++]); return r; })()),
    /* 76 GPUQueue.writeBuffer */ () => H(A[I++]).writeBuffer(H(A[I++]), A[I++], S[A[I++]], (A[I++] ? A[I++] : undefined), (A[I++] ? A[I++] : undefined)),
    /* 77 GPUQueue.writeTexture */ () => H(A[I++]).writeTexture(D_GPUTexelCopyTextureInfo(), S[A[I++]], D_GPUTexelCopyBufferLayout(), D_GPUExtent3DDict()),
    /* 78 GPUQueue.copyExternalImageToTexture */ () => H(A[I++]).copyExternalImageToTexture(D_GPUCopyExternalImageSourceInfo(), D_GPUCopyExternalImageDestInfo(), D_GPUExtent3DDict()),
    /* 79 GPUQuerySet.destroy */ () => H(A[I++]).destroy(),
    /* 80 GPUCanvasContext.configure */ () => H(A[I++]).configure(D_GPUCanvasConfiguration()),
    /* 81 GPUCanvasContext.unconfigure */ () => H(A[I++]).unconfigure(),
    /* 82 GPUCanvasContext.getCurrentTexture */ () => REG(H(A[I++]).getCurrentTexture()),
  ];
  return { gpuRun: (p, n, s) => {
    A = new Float64Array(mem(), p >>> 0, n); I = 0; S = s;
    let r = 0;
    while (I < n) r = M[A[I++]]();
    A = null; S = null;
    return typeof r === 'number' ? r : (r ? 1 : 0);
  } };
};
