<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="LexerTests.fs" />
    <Compile Include="ParserTests.fs" />
    <Compile Include="QueryTests.fs" />
    <Compile Include="WorkspaceTests.fs" />
    <Compile Include="ResolveTests.fs" />
    <Compile Include="InferTests.fs" />
    <Compile Include="ProjectTests.fs" />
    <Compile Include="LowerTests.fs" />
    <Compile Include="EmitTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Expecto" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Fpp.Compiler/Fpp.Compiler.fsproj" />
    <ProjectReference Include="../../src/Fpp.Lsp/Fpp.Lsp.fsproj" />
  </ItemGroup>

</Project>
